version: '3'
services:
  socket-server:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://highland-eight.vercel.app/
    restart: unless-stopped 